{% extends 'layout.swig' %}
{% block content%}
<nav>
    <div class="nav-wrapper teal">
      <a href="#" class="brand-logo right">Micasa</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="login">Login</a></li>
        <li><a href="signup">Sign up</a></li>
        <li><a href="search">Serach</a></li>
      </ul>
    </div>
  </nav>
 <br><center><img src="images/micasa.png" style = "width:400px;height:400x;"></center><br>
  <h4 class="header center orange-text">Welcome Agent </h4>
{% endblock %}